#!/bin/sh -e

# Rebuild initramfs.gz after kernel upgrade to include new kernel's modules.
# https://github.com/Robpol86/robpol86.com/blob/master/docs/_static/initramfs-rebuild.sh
# Save as (chmod +x): /etc/kernel/postinst.d/initramfs-rebuild

rasp_boot_dir="/boot/firmware"

# Remove splash from cmdline.
if grep -q '\bsplash\b' ${rasp_boot_dir}/cmdline.txt; then
  sed -i 's/ \?splash \?/ /' ${rasp_boot_dir}/cmdline.txt
fi

# Exit if not building kernel for this Raspberry Pi's hardware version.
version="$1"
current_version="$(uname -r)"
case "${current_version}" in
  *-v7+)
    case "${version}" in
      *-v7+) ;;
      *) exit 0
    esac
  ;;
  *+)
    case "${version}" in
      *-v7+) exit 0 ;;
    esac
  ;;
esac

# Exit if rebuild cannot be performed or not needed.
[ -x /usr/sbin/mkinitramfs ] || exit 0
[ -f ${rasp_boot_dir}/initramfs.gz ] || exit 0
lsinitramfs ${rasp_boot_dir}/initramfs.gz |grep -q "/$version$" && exit 0  # Already in initramfs.

# Rebuild.
mkinitramfs -o ${rasp_boot_dir}/initramfs.gz "$version"